### ISSUE TITLE
Permission for the anti-alias image

### ISSUE THREAD

**Issue by csgillespie** [rweekly/image#3]
@MilesMcBain asked for permission to use this image
![2020-r-graphics-anti-aliasing](https://user-images.githubusercontent.com/1267747/79692690-7504b180-825e-11ea-8842-f650c95a3ddd.png)

Feel free to use this (or any other) image from the blog post

---

Sorry I wasn't sure where to upload

**Comment by MilesMcBain** [comment]
Thanks! I do the uploading, just after the permission :+1:
